# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'visu_resultat_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        DockWidget.setObjectName("DockWidget")
        DockWidget.resize(461, 652)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(150)
        sizePolicy.setHeightForWidth(DockWidget.sizePolicy().hasHeightForWidth())
        DockWidget.setSizePolicy(sizePolicy)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.btFermer = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btFermer.setGeometry(QtCore.QRect(400, 530, 51, 30))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/VisuValideMultiCriteriaMatching/img/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btFermer.setIcon(icon)
        self.btFermer.setIconSize(QtCore.QSize(18, 18))
        self.btFermer.setObjectName("btFermer")
        self.label_grille = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.label_grille.setGeometry(QtCore.QRect(10, 60, 371, 71))
        self.label_grille.setObjectName("label_grille")
        self.btSuiv = QtWidgets.QPushButton(self.label_grille)
        self.btSuiv.setGeometry(QtCore.QRect(300, 30, 61, 23))
        self.btSuiv.setObjectName("btSuiv")
        self.btPrec = QtWidgets.QPushButton(self.label_grille)
        self.btPrec.setGeometry(QtCore.QRect(240, 30, 61, 23))
        self.btPrec.setObjectName("btPrec")
        self.currentId = QtWidgets.QLineEdit(self.label_grille)
        self.currentId.setGeometry(QtCore.QRect(170, 30, 61, 21))
        self.currentId.setObjectName("currentId")
        self.label_cell_encours = QtWidgets.QLabel(self.label_grille)
        self.label_cell_encours.setGeometry(QtCore.QRect(10, 30, 151, 20))
        self.label_cell_encours.setObjectName("label_cell_encours")
        self.btZoomGrille = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btZoomGrille.setGeometry(QtCore.QRect(400, 490, 51, 30))
        self.btZoomGrille.setObjectName("btZoomGrille")
        self.tableCoordFeu = QtWidgets.QTableWidget(self.dockWidgetContents)
        self.tableCoordFeu.setGeometry(QtCore.QRect(10, 140, 451, 161))
        self.tableCoordFeu.setRowCount(5)
        self.tableCoordFeu.setColumnCount(4)
        self.tableCoordFeu.setObjectName("tableCoordFeu")
        self.tableCoordFeu.horizontalHeader().setDefaultSectionSize(108)
        self.tableCoordFeu.horizontalHeader().setMinimumSectionSize(30)
        self.tableCoordFeu.verticalHeader().setDefaultSectionSize(30)
        self.tableCoordFeu.verticalHeader().setMinimumSectionSize(15)
        self.fileResultat = gui.QgsFileWidget(self.dockWidgetContents)
        self.fileResultat.setGeometry(QtCore.QRect(40, 30, 291, 27))
        self.fileResultat.setObjectName("fileResultat")
        self.label_importer = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_importer.setGeometry(QtCore.QRect(10, 10, 251, 16))
        self.label_importer.setObjectName("label_importer")
        self.labelSeuil1 = QtWidgets.QLabel(self.dockWidgetContents)
        self.labelSeuil1.setGeometry(QtCore.QRect(20, 350, 111, 20))
        self.labelSeuil1.setObjectName("labelSeuil1")
        self.D1_T1 = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.D1_T1.setGeometry(QtCore.QRect(140, 350, 70, 20))
        self.D1_T1.setText("")
        self.D1_T1.setObjectName("D1_T1")
        self.D1_T2 = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.D1_T2.setGeometry(QtCore.QRect(210, 350, 70, 20))
        self.D1_T2.setText("")
        self.D1_T2.setObjectName("D1_T2")
        self.labelSeuil2 = QtWidgets.QLabel(self.dockWidgetContents)
        self.labelSeuil2.setGeometry(QtCore.QRect(20, 370, 111, 20))
        self.labelSeuil2.setObjectName("labelSeuil2")
        self.labelSeuil3 = QtWidgets.QLabel(self.dockWidgetContents)
        self.labelSeuil3.setEnabled(False)
        self.labelSeuil3.setGeometry(QtCore.QRect(20, 390, 111, 20))
        self.labelSeuil3.setObjectName("labelSeuil3")
        self.labelSeuil4 = QtWidgets.QLabel(self.dockWidgetContents)
        self.labelSeuil4.setEnabled(False)
        self.labelSeuil4.setGeometry(QtCore.QRect(20, 410, 111, 20))
        self.labelSeuil4.setObjectName("labelSeuil4")
        self.D2_T1 = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.D2_T1.setGeometry(QtCore.QRect(140, 370, 70, 20))
        self.D2_T1.setText("")
        self.D2_T1.setObjectName("D2_T1")
        self.D3_T1 = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.D3_T1.setEnabled(False)
        self.D3_T1.setGeometry(QtCore.QRect(140, 390, 70, 20))
        self.D3_T1.setText("")
        self.D3_T1.setObjectName("D3_T1")
        self.D4_T1 = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.D4_T1.setEnabled(False)
        self.D4_T1.setGeometry(QtCore.QRect(140, 410, 70, 20))
        self.D4_T1.setText("")
        self.D4_T1.setObjectName("D4_T1")
        self.D2_T2 = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.D2_T2.setGeometry(QtCore.QRect(210, 370, 70, 20))
        self.D2_T2.setText("")
        self.D2_T2.setObjectName("D2_T2")
        self.D3_T2 = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.D3_T2.setEnabled(False)
        self.D3_T2.setGeometry(QtCore.QRect(210, 390, 70, 20))
        self.D3_T2.setText("")
        self.D3_T2.setObjectName("D3_T2")
        self.D4_T2 = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.D4_T2.setEnabled(False)
        self.D4_T2.setGeometry(QtCore.QRect(210, 410, 70, 20))
        self.D4_T2.setText("")
        self.D4_T2.setObjectName("D4_T2")
        self.label_8 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_8.setGeometry(QtCore.QRect(170, 330, 21, 20))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_9.setGeometry(QtCore.QRect(240, 330, 21, 20))
        self.label_9.setObjectName("label_9")
        self.labelSeuil5 = QtWidgets.QLabel(self.dockWidgetContents)
        self.labelSeuil5.setEnabled(False)
        self.labelSeuil5.setGeometry(QtCore.QRect(20, 430, 111, 20))
        self.labelSeuil5.setObjectName("labelSeuil5")
        self.D5_T1 = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.D5_T1.setEnabled(False)
        self.D5_T1.setGeometry(QtCore.QRect(140, 430, 70, 20))
        self.D5_T1.setText("")
        self.D5_T1.setObjectName("D5_T1")
        self.D5_T2 = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.D5_T2.setEnabled(False)
        self.D5_T2.setGeometry(QtCore.QRect(210, 430, 70, 20))
        self.D5_T2.setText("")
        self.D5_T2.setObjectName("D5_T2")
        self.groupBox = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.groupBox.setGeometry(QtCore.QRect(30, 490, 341, 131))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(40, 30, 53, 16))
        self.label.setObjectName("label")
        self.pign1 = QtWidgets.QLineEdit(self.groupBox)
        self.pign1.setGeometry(QtCore.QRect(90, 30, 113, 22))
        self.pign1.setObjectName("pign1")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(40, 60, 53, 16))
        self.label_2.setObjectName("label_2")
        self.pign2 = QtWidgets.QLineEdit(self.groupBox)
        self.pign2.setGeometry(QtCore.QRect(90, 60, 113, 22))
        self.pign2.setObjectName("pign2")
        self.labelResultat = QtWidgets.QLineEdit(self.groupBox)
        self.labelResultat.setGeometry(QtCore.QRect(40, 90, 291, 25))
        self.labelResultat.setObjectName("labelResultat")
        self.label_3 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_3.setGeometry(QtCore.QRect(20, 460, 111, 17))
        self.label_3.setObjectName("label_3")
        self.seuilP = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.seuilP.setGeometry(QtCore.QRect(140, 460, 141, 21))
        self.seuilP.setObjectName("seuilP")
        self.rbID = QtWidgets.QRadioButton(self.dockWidgetContents)
        self.rbID.setGeometry(QtCore.QRect(300, 320, 112, 23))
        self.rbID.setText("")
        self.rbID.setChecked(True)
        self.rbID.setObjectName("rbID")
        self.rbD1 = QtWidgets.QRadioButton(self.dockWidgetContents)
        self.rbD1.setGeometry(QtCore.QRect(300, 350, 112, 23))
        self.rbD1.setText("")
        self.rbD1.setObjectName("rbD1")
        self.rbD2 = QtWidgets.QRadioButton(self.dockWidgetContents)
        self.rbD2.setGeometry(QtCore.QRect(300, 370, 112, 23))
        self.rbD2.setText("")
        self.rbD2.setObjectName("rbD2")
        self.rbD3 = QtWidgets.QRadioButton(self.dockWidgetContents)
        self.rbD3.setEnabled(False)
        self.rbD3.setGeometry(QtCore.QRect(300, 390, 112, 23))
        self.rbD3.setText("")
        self.rbD3.setObjectName("rbD3")
        self.rbD4 = QtWidgets.QRadioButton(self.dockWidgetContents)
        self.rbD4.setEnabled(False)
        self.rbD4.setGeometry(QtCore.QRect(300, 410, 112, 23))
        self.rbD4.setText("")
        self.rbD4.setObjectName("rbD4")
        self.rbD5 = QtWidgets.QRadioButton(self.dockWidgetContents)
        self.rbD5.setEnabled(False)
        self.rbD5.setGeometry(QtCore.QRect(300, 430, 112, 23))
        self.rbD5.setText("")
        self.rbD5.setObjectName("rbD5")
        self.label_grille.raise_()
        self.btFermer.raise_()
        self.btZoomGrille.raise_()
        self.tableCoordFeu.raise_()
        self.fileResultat.raise_()
        self.label_importer.raise_()
        self.labelSeuil1.raise_()
        self.D1_T1.raise_()
        self.D1_T2.raise_()
        self.labelSeuil2.raise_()
        self.labelSeuil3.raise_()
        self.labelSeuil4.raise_()
        self.D2_T1.raise_()
        self.D3_T1.raise_()
        self.D4_T1.raise_()
        self.D2_T2.raise_()
        self.D3_T2.raise_()
        self.D4_T2.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.labelSeuil5.raise_()
        self.D5_T1.raise_()
        self.D5_T2.raise_()
        self.groupBox.raise_()
        self.label_3.raise_()
        self.seuilP.raise_()
        self.rbID.raise_()
        self.rbD1.raise_()
        self.rbD2.raise_()
        self.rbD3.raise_()
        self.rbD4.raise_()
        self.rbD5.raise_()
        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)

    def retranslateUi(self, DockWidget):
        _translate = QtCore.QCoreApplication.translate
        DockWidget.setWindowTitle(_translate("DockWidget", "Validation des résultats d\'appariement"))
        self.btFermer.setToolTip(_translate("DockWidget", "Fermer le plugin"))
        self.btFermer.setText(_translate("DockWidget", "Close"))
        self.label_grille.setTitle(_translate("DockWidget", "Lecture"))
        self.btSuiv.setText(_translate("DockWidget", ">>"))
        self.btPrec.setText(_translate("DockWidget", "<<"))
        self.label_cell_encours.setText(_translate("DockWidget", "Feature ref en cours:"))
        self.btZoomGrille.setText(_translate("DockWidget", "Zoom "))
        self.label_importer.setText(_translate("DockWidget", "Fichier de résultat des appariements:"))
        self.labelSeuil1.setText(_translate("DockWidget", "Seuils distance 1:"))
        self.labelSeuil2.setText(_translate("DockWidget", "Seuils distance 2:"))
        self.labelSeuil3.setText(_translate("DockWidget", "Seuils distance 3:"))
        self.labelSeuil4.setText(_translate("DockWidget", "Seuils distance 4:"))
        self.label_8.setText(_translate("DockWidget", "T1"))
        self.label_9.setText(_translate("DockWidget", "T2"))
        self.labelSeuil5.setText(_translate("DockWidget", "Seuils distance 5:"))
        self.label.setText(_translate("DockWidget", "Pign 1:"))
        self.label_2.setText(_translate("DockWidget", "Pign 2:"))
        self.label_3.setText(_translate("DockWidget", "Seuil précision:"))
from qgis import gui
