# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'visu_resultat_dialog_base.ui'
#
# Created: Sun Aug 18 20:55:57 2019
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        DockWidget.setObjectName(_fromUtf8("DockWidget"))
        DockWidget.resize(397, 631)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(150)
        sizePolicy.setHeightForWidth(DockWidget.sizePolicy().hasHeightForWidth())
        DockWidget.setSizePolicy(sizePolicy)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.btFermer = QtGui.QPushButton(self.dockWidgetContents)
        self.btFermer.setGeometry(QtCore.QRect(260, 550, 111, 30))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/VisuValideMultiCriteriaMatching/img/close.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btFermer.setIcon(icon)
        self.btFermer.setIconSize(QtCore.QSize(18, 18))
        self.btFermer.setObjectName(_fromUtf8("btFermer"))
        self.label_grille = QtGui.QGroupBox(self.dockWidgetContents)
        self.label_grille.setGeometry(QtCore.QRect(10, 70, 371, 101))
        self.label_grille.setObjectName(_fromUtf8("label_grille"))
        self.btSuiv = QtGui.QPushButton(self.label_grille)
        self.btSuiv.setGeometry(QtCore.QRect(190, 60, 111, 23))
        self.btSuiv.setObjectName(_fromUtf8("btSuiv"))
        self.btPrec = QtGui.QPushButton(self.label_grille)
        self.btPrec.setGeometry(QtCore.QRect(80, 60, 111, 23))
        self.btPrec.setObjectName(_fromUtf8("btPrec"))
        self.currentId = QtGui.QLineEdit(self.label_grille)
        self.currentId.setGeometry(QtCore.QRect(170, 20, 61, 21))
        self.currentId.setObjectName(_fromUtf8("currentId"))
        self.label_cell_encours = QtGui.QLabel(self.label_grille)
        self.label_cell_encours.setGeometry(QtCore.QRect(20, 20, 131, 20))
        self.label_cell_encours.setObjectName(_fromUtf8("label_cell_encours"))
        self.btZoomGrille = QtGui.QPushButton(self.dockWidgetContents)
        self.btZoomGrille.setGeometry(QtCore.QRect(150, 550, 111, 30))
        self.btZoomGrille.setObjectName(_fromUtf8("btZoomGrille"))
        self.tableCoordFeu = QtGui.QTableWidget(self.dockWidgetContents)
        self.tableCoordFeu.setGeometry(QtCore.QRect(10, 180, 381, 201))
        self.tableCoordFeu.setRowCount(5)
        self.tableCoordFeu.setColumnCount(3)
        self.tableCoordFeu.setObjectName(_fromUtf8("tableCoordFeu"))
        self.tableCoordFeu.horizontalHeader().setDefaultSectionSize(108)
        self.tableCoordFeu.horizontalHeader().setMinimumSectionSize(30)
        self.tableCoordFeu.verticalHeader().setDefaultSectionSize(30)
        self.tableCoordFeu.verticalHeader().setMinimumSectionSize(15)
        self.fileResultat = QgsFileWidget(self.dockWidgetContents)
        self.fileResultat.setGeometry(QtCore.QRect(70, 30, 301, 27))
        self.fileResultat.setObjectName(_fromUtf8("fileResultat"))
        self.label_importer = QtGui.QLabel(self.dockWidgetContents)
        self.label_importer.setGeometry(QtCore.QRect(10, 10, 251, 16))
        self.label_importer.setObjectName(_fromUtf8("label_importer"))
        self.labelSeuil1 = QtGui.QLabel(self.dockWidgetContents)
        self.labelSeuil1.setGeometry(QtCore.QRect(50, 410, 111, 20))
        self.labelSeuil1.setObjectName(_fromUtf8("labelSeuil1"))
        self.D1_T1 = QtGui.QLineEdit(self.dockWidgetContents)
        self.D1_T1.setGeometry(QtCore.QRect(170, 410, 70, 20))
        self.D1_T1.setText(_fromUtf8(""))
        self.D1_T1.setObjectName(_fromUtf8("D1_T1"))
        self.D1_T2 = QtGui.QLineEdit(self.dockWidgetContents)
        self.D1_T2.setGeometry(QtCore.QRect(240, 410, 70, 20))
        self.D1_T2.setText(_fromUtf8(""))
        self.D1_T2.setObjectName(_fromUtf8("D1_T2"))
        self.labelSeuil2 = QtGui.QLabel(self.dockWidgetContents)
        self.labelSeuil2.setGeometry(QtCore.QRect(50, 430, 111, 20))
        self.labelSeuil2.setObjectName(_fromUtf8("labelSeuil2"))
        self.labelSeuil3 = QtGui.QLabel(self.dockWidgetContents)
        self.labelSeuil3.setEnabled(False)
        self.labelSeuil3.setGeometry(QtCore.QRect(50, 450, 111, 20))
        self.labelSeuil3.setObjectName(_fromUtf8("labelSeuil3"))
        self.labelSeuil4 = QtGui.QLabel(self.dockWidgetContents)
        self.labelSeuil4.setEnabled(False)
        self.labelSeuil4.setGeometry(QtCore.QRect(50, 470, 111, 20))
        self.labelSeuil4.setObjectName(_fromUtf8("labelSeuil4"))
        self.D2_T1 = QtGui.QLineEdit(self.dockWidgetContents)
        self.D2_T1.setGeometry(QtCore.QRect(170, 430, 70, 20))
        self.D2_T1.setText(_fromUtf8(""))
        self.D2_T1.setObjectName(_fromUtf8("D2_T1"))
        self.D3_T1 = QtGui.QLineEdit(self.dockWidgetContents)
        self.D3_T1.setEnabled(False)
        self.D3_T1.setGeometry(QtCore.QRect(170, 450, 70, 20))
        self.D3_T1.setText(_fromUtf8(""))
        self.D3_T1.setObjectName(_fromUtf8("D3_T1"))
        self.D4_T1 = QtGui.QLineEdit(self.dockWidgetContents)
        self.D4_T1.setEnabled(False)
        self.D4_T1.setGeometry(QtCore.QRect(170, 470, 70, 20))
        self.D4_T1.setText(_fromUtf8(""))
        self.D4_T1.setObjectName(_fromUtf8("D4_T1"))
        self.D2_T2 = QtGui.QLineEdit(self.dockWidgetContents)
        self.D2_T2.setGeometry(QtCore.QRect(240, 430, 70, 20))
        self.D2_T2.setText(_fromUtf8(""))
        self.D2_T2.setObjectName(_fromUtf8("D2_T2"))
        self.D3_T2 = QtGui.QLineEdit(self.dockWidgetContents)
        self.D3_T2.setEnabled(False)
        self.D3_T2.setGeometry(QtCore.QRect(240, 450, 70, 20))
        self.D3_T2.setText(_fromUtf8(""))
        self.D3_T2.setObjectName(_fromUtf8("D3_T2"))
        self.D4_T2 = QtGui.QLineEdit(self.dockWidgetContents)
        self.D4_T2.setEnabled(False)
        self.D4_T2.setGeometry(QtCore.QRect(240, 470, 70, 20))
        self.D4_T2.setText(_fromUtf8(""))
        self.D4_T2.setObjectName(_fromUtf8("D4_T2"))
        self.label_8 = QtGui.QLabel(self.dockWidgetContents)
        self.label_8.setGeometry(QtCore.QRect(200, 390, 21, 20))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.dockWidgetContents)
        self.label_9.setGeometry(QtCore.QRect(270, 390, 21, 20))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.labelSeuil5 = QtGui.QLabel(self.dockWidgetContents)
        self.labelSeuil5.setEnabled(False)
        self.labelSeuil5.setGeometry(QtCore.QRect(50, 490, 111, 20))
        self.labelSeuil5.setObjectName(_fromUtf8("labelSeuil5"))
        self.D5_T1 = QtGui.QLineEdit(self.dockWidgetContents)
        self.D5_T1.setEnabled(False)
        self.D5_T1.setGeometry(QtCore.QRect(170, 490, 70, 20))
        self.D5_T1.setText(_fromUtf8(""))
        self.D5_T1.setObjectName(_fromUtf8("D5_T1"))
        self.D5_T2 = QtGui.QLineEdit(self.dockWidgetContents)
        self.D5_T2.setEnabled(False)
        self.D5_T2.setGeometry(QtCore.QRect(240, 490, 70, 20))
        self.D5_T2.setText(_fromUtf8(""))
        self.D5_T2.setObjectName(_fromUtf8("D5_T2"))
        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)

    def retranslateUi(self, DockWidget):
        DockWidget.setWindowTitle(_translate("DockWidget", "VisuResultat", None))
        self.btFermer.setToolTip(_translate("DockWidget", "Fermer le plugin", None))
        self.btFermer.setText(_translate("DockWidget", "Fermer", None))
        self.label_grille.setTitle(_translate("DockWidget", "Lecture", None))
        self.btSuiv.setText(_translate("DockWidget", ">>", None))
        self.btPrec.setText(_translate("DockWidget", "<<", None))
        self.label_cell_encours.setText(_translate("DockWidget", "Feature ref en cours:", None))
        self.btZoomGrille.setText(_translate("DockWidget", "Zoom  ref", None))
        self.label_importer.setText(_translate("DockWidget", "Fichier de résultat:", None))
        self.labelSeuil1.setText(_translate("DockWidget", "Seuils distance 1:", None))
        self.labelSeuil2.setText(_translate("DockWidget", "Seuils distance 2:", None))
        self.labelSeuil3.setText(_translate("DockWidget", "Seuils distance 3:", None))
        self.labelSeuil4.setText(_translate("DockWidget", "Seuils distance 4:", None))
        self.label_8.setText(_translate("DockWidget", "T1", None))
        self.label_9.setText(_translate("DockWidget", "T2", None))
        self.labelSeuil5.setText(_translate("DockWidget", "Seuils distance 5:", None))

from qgis.gui import QgsFileWidget
