# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'visu_resultat_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        DockWidget.setObjectName("DockWidget")
        DockWidget.resize(397, 681)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(150)
        sizePolicy.setHeightForWidth(DockWidget.sizePolicy().hasHeightForWidth())
        DockWidget.setSizePolicy(sizePolicy)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.btFermer = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btFermer.setGeometry(QtCore.QRect(240, 610, 111, 30))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/VisuValideMultiCriteriaMatching/img/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btFermer.setIcon(icon)
        self.btFermer.setIconSize(QtCore.QSize(18, 18))
        self.btFermer.setObjectName("btFermer")
        self.label_grille = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.label_grille.setGeometry(QtCore.QRect(10, 70, 351, 101))
        self.label_grille.setObjectName("label_grille")
        self.btSuiv = QtWidgets.QPushButton(self.label_grille)
        self.btSuiv.setGeometry(QtCore.QRect(190, 60, 111, 23))
        self.btSuiv.setObjectName("btSuiv")
        self.btPrec = QtWidgets.QPushButton(self.label_grille)
        self.btPrec.setGeometry(QtCore.QRect(80, 60, 111, 23))
        self.btPrec.setObjectName("btPrec")
        self.currentId = QtWidgets.QLineEdit(self.label_grille)
        self.currentId.setGeometry(QtCore.QRect(170, 20, 61, 21))
        self.currentId.setObjectName("currentId")
        self.label_cell_encours = QtWidgets.QLabel(self.label_grille)
        self.label_cell_encours.setGeometry(QtCore.QRect(20, 20, 131, 20))
        self.label_cell_encours.setObjectName("label_cell_encours")
        self.btZoomGrille = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btZoomGrille.setGeometry(QtCore.QRect(130, 610, 111, 30))
        self.btZoomGrille.setObjectName("btZoomGrille")
        self.tableCoordFeu = QtWidgets.QTableWidget(self.dockWidgetContents)
        self.tableCoordFeu.setGeometry(QtCore.QRect(10, 180, 351, 161))
        self.tableCoordFeu.setRowCount(5)
        self.tableCoordFeu.setColumnCount(3)
        self.tableCoordFeu.setObjectName("tableCoordFeu")
        self.tableCoordFeu.horizontalHeader().setDefaultSectionSize(108)
        self.tableCoordFeu.horizontalHeader().setMinimumSectionSize(30)
        self.tableCoordFeu.verticalHeader().setDefaultSectionSize(30)
        self.tableCoordFeu.verticalHeader().setMinimumSectionSize(15)
        self.fileResultat = QgsFileWidget(self.dockWidgetContents)
        self.fileResultat.setGeometry(QtCore.QRect(70, 30, 271, 27))
        self.fileResultat.setObjectName("fileResultat")
        self.label_importer = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_importer.setGeometry(QtCore.QRect(10, 10, 251, 16))
        self.label_importer.setObjectName("label_importer")
        self.labelSeuil1 = QtWidgets.QLabel(self.dockWidgetContents)
        self.labelSeuil1.setGeometry(QtCore.QRect(20, 370, 111, 20))
        self.labelSeuil1.setObjectName("labelSeuil1")
        self.D1_T1 = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.D1_T1.setGeometry(QtCore.QRect(140, 370, 70, 20))
        self.D1_T1.setText("")
        self.D1_T1.setObjectName("D1_T1")
        self.D1_T2 = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.D1_T2.setGeometry(QtCore.QRect(210, 370, 70, 20))
        self.D1_T2.setText("")
        self.D1_T2.setObjectName("D1_T2")
        self.labelSeuil2 = QtWidgets.QLabel(self.dockWidgetContents)
        self.labelSeuil2.setGeometry(QtCore.QRect(20, 390, 111, 20))
        self.labelSeuil2.setObjectName("labelSeuil2")
        self.labelSeuil3 = QtWidgets.QLabel(self.dockWidgetContents)
        self.labelSeuil3.setEnabled(False)
        self.labelSeuil3.setGeometry(QtCore.QRect(20, 410, 111, 20))
        self.labelSeuil3.setObjectName("labelSeuil3")
        self.labelSeuil4 = QtWidgets.QLabel(self.dockWidgetContents)
        self.labelSeuil4.setEnabled(False)
        self.labelSeuil4.setGeometry(QtCore.QRect(20, 430, 111, 20))
        self.labelSeuil4.setObjectName("labelSeuil4")
        self.D2_T1 = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.D2_T1.setGeometry(QtCore.QRect(140, 390, 70, 20))
        self.D2_T1.setText("")
        self.D2_T1.setObjectName("D2_T1")
        self.D3_T1 = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.D3_T1.setEnabled(False)
        self.D3_T1.setGeometry(QtCore.QRect(140, 410, 70, 20))
        self.D3_T1.setText("")
        self.D3_T1.setObjectName("D3_T1")
        self.D4_T1 = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.D4_T1.setEnabled(False)
        self.D4_T1.setGeometry(QtCore.QRect(140, 430, 70, 20))
        self.D4_T1.setText("")
        self.D4_T1.setObjectName("D4_T1")
        self.D2_T2 = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.D2_T2.setGeometry(QtCore.QRect(210, 390, 70, 20))
        self.D2_T2.setText("")
        self.D2_T2.setObjectName("D2_T2")
        self.D3_T2 = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.D3_T2.setEnabled(False)
        self.D3_T2.setGeometry(QtCore.QRect(210, 410, 70, 20))
        self.D3_T2.setText("")
        self.D3_T2.setObjectName("D3_T2")
        self.D4_T2 = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.D4_T2.setEnabled(False)
        self.D4_T2.setGeometry(QtCore.QRect(210, 430, 70, 20))
        self.D4_T2.setText("")
        self.D4_T2.setObjectName("D4_T2")
        self.label_8 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_8.setGeometry(QtCore.QRect(170, 350, 21, 20))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_9.setGeometry(QtCore.QRect(240, 350, 21, 20))
        self.label_9.setObjectName("label_9")
        self.labelSeuil5 = QtWidgets.QLabel(self.dockWidgetContents)
        self.labelSeuil5.setEnabled(False)
        self.labelSeuil5.setGeometry(QtCore.QRect(20, 450, 111, 20))
        self.labelSeuil5.setObjectName("labelSeuil5")
        self.D5_T1 = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.D5_T1.setEnabled(False)
        self.D5_T1.setGeometry(QtCore.QRect(140, 450, 70, 20))
        self.D5_T1.setText("")
        self.D5_T1.setObjectName("D5_T1")
        self.D5_T2 = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.D5_T2.setEnabled(False)
        self.D5_T2.setGeometry(QtCore.QRect(210, 450, 70, 20))
        self.D5_T2.setText("")
        self.D5_T2.setObjectName("D5_T2")
        self.groupBox = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.groupBox.setGeometry(QtCore.QRect(10, 490, 341, 111))
        self.groupBox.setObjectName("groupBox")
        self.labelResultat = QtWidgets.QLabel(self.groupBox)
        self.labelResultat.setGeometry(QtCore.QRect(100, 20, 200, 16))
        self.labelResultat.setObjectName("labelResultat")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(40, 50, 53, 16))
        self.label.setObjectName("label")
        self.pign1 = QtWidgets.QLineEdit(self.groupBox)
        self.pign1.setGeometry(QtCore.QRect(90, 50, 113, 22))
        self.pign1.setObjectName("pign1")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(40, 70, 53, 16))
        self.label_2.setObjectName("label_2")
        self.pign2 = QtWidgets.QLineEdit(self.groupBox)
        self.pign2.setGeometry(QtCore.QRect(90, 70, 113, 22))
        self.pign2.setObjectName("pign2")
        self.label_grille.raise_()
        self.btFermer.raise_()
        self.btZoomGrille.raise_()
        self.tableCoordFeu.raise_()
        self.fileResultat.raise_()
        self.label_importer.raise_()
        self.labelSeuil1.raise_()
        self.D1_T1.raise_()
        self.D1_T2.raise_()
        self.labelSeuil2.raise_()
        self.labelSeuil3.raise_()
        self.labelSeuil4.raise_()
        self.D2_T1.raise_()
        self.D3_T1.raise_()
        self.D4_T1.raise_()
        self.D2_T2.raise_()
        self.D3_T2.raise_()
        self.D4_T2.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.labelSeuil5.raise_()
        self.D5_T1.raise_()
        self.D5_T2.raise_()
        self.groupBox.raise_()
        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)

    def retranslateUi(self, DockWidget):
        _translate = QtCore.QCoreApplication.translate
        DockWidget.setWindowTitle(_translate("DockWidget", "Visualisation des résultats d\'appariement"))
        self.btFermer.setToolTip(_translate("DockWidget", "Fermer le plugin"))
        self.btFermer.setText(_translate("DockWidget", "Fermer"))
        self.label_grille.setTitle(_translate("DockWidget", "Lecture"))
        self.btSuiv.setText(_translate("DockWidget", ">>"))
        self.btPrec.setText(_translate("DockWidget", "<<"))
        self.label_cell_encours.setText(_translate("DockWidget", "Feature ref en cours:"))
        self.btZoomGrille.setText(_translate("DockWidget", "Zoom  ref"))
        self.label_importer.setText(_translate("DockWidget", "Fichier de résultat:"))
        self.labelSeuil1.setText(_translate("DockWidget", "Seuils distance 1:"))
        self.labelSeuil2.setText(_translate("DockWidget", "Seuils distance 2:"))
        self.labelSeuil3.setText(_translate("DockWidget", "Seuils distance 3:"))
        self.labelSeuil4.setText(_translate("DockWidget", "Seuils distance 4:"))
        self.label_8.setText(_translate("DockWidget", "T1"))
        self.label_9.setText(_translate("DockWidget", "T2"))
        self.labelSeuil5.setText(_translate("DockWidget", "Seuils distance 5:"))
        self.groupBox.setTitle(_translate("DockWidget", "Résultat"))
        self.labelResultat.setText(_translate("DockWidget", "..."))
        self.label.setText(_translate("DockWidget", "Pign 1:"))
        self.label_2.setText(_translate("DockWidget", "Pign 2:"))

from qgis.gui import QgsFileWidget
